import importlib.resources as resources
import os
from unittest import mock

import numpy as np
import pandas as pd
import pyarrow.dataset as ds
from toshi_hazard_store.model.pyarrow import pyarrow_dataset

from toshi_hazard_post.aggregation import run_aggregation
from toshi_hazard_post.aggregation_args import load_input_args

fixture_dir = resources.files('tests.fixtures.end_to_end')
parquet_filepath = fixture_dir / 'rlz_probs_WLG.pq'
args_filepath = fixture_dir / 'hazard.toml'

# this fixture was generated by toshi-hazard-post-v1
aggs_expected_filepath = fixture_dir / 'aggregations_275_PGA_WLG.npy'


@mock.patch('toshi_hazard_post.aggregation_calc.load_realizations')
def test_end_to_end(load_mock, tmp_path):
    probs_expected = np.load(aggs_expected_filepath)

    os.environ["THP_AGG_DIR"] = str(tmp_path)
    os.environ["THP_NUM_WORKERS"] = "1"

    load_mock.return_value = pd.read_parquet(parquet_filepath)
    agg_args = load_input_args(args_filepath)

    print(agg_args)

    run_aggregation(agg_args)

    # read the aggregation back out and compare
    rlz_dir, filesystem = pyarrow_dataset.configure_output(str(tmp_path))
    dataset = ds.dataset(rlz_dir, format="parquet", filesystem=filesystem, partitioning="hive")
    probs = np.stack(ds.Scanner.from_dataset(dataset).to_table().to_pandas()['values'].values)

    np.testing.assert_allclose(probs, probs_expected, rtol=1e-07, atol=1e-08)
