[aggregation]
hazard_model_id = "TEST"
stage = "PROD"
vs30s = [250]
# imts = ['PGA', 'SA(1.5)']
imts = ['PGA']
aggs = ["mean", "cov", "std", "0.005", "0.01", "0.025", "0.05", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "0.95", "0.975", "0.99", "0.995"]
# locations = ["-44.251~170.800", "-43.539~172.603"]
locations = ["-44.251~170.800"]
logic_tree_file = "demo/SLT_v9p0p0.py"
gtids = ["R2VuZXJhbFRhc2s6NjUzNjgwNg=="]

[debug]
skip_save = true