[aggregation]
hazard_model_id = "SLT_TAG_FINAL"
description = "Source Logic Tree TAG_FINAL 0.1 degree GT: R2VuZXJhbFRhc2s6MTA4NTU5"
stage = "PROD"
vs30s = [ 400 ]
imts = ["PGA", "SA(0.1)", "SA(0.2)", "SA(0.3)", "SA(0.4)", "SA(0.5)", "SA(0.7)", "SA(1.0)", "SA(1.5)", "SA(2.0)", "SA(3.0)", "SA(4.0)", "SA(5.0)"]
aggs = ["mean", "0.005", "0.1", "0.2", "0.5", "0.8", "0.9", "0.995"]
locations = "NZ_0_1_NB_1_0" # this is the one matching the old CSV
logic_tree_file = "SLT_TAG_FINAL_0.1.json"

[debug]
# location_limit = 32
# source_branches_truncate = 10
reuse_source_branches_id = "RmlsZToxMTgwMDA=" # FULL source_branches.json from
