[aggregation]
description = "Source Logic Tree TAG_FINAL"
stage = "PROD"
vs30s = [ 400 ]
imts = ["PGA", "SA(0.1)", "SA(0.2)", "SA(0.3)", "SA(0.4)", "SA(0.5)", "SA(0.7)", "SA(1.0)", "SA(1.5)", "SA(2.0)", "SA(3.0)", "SA(4.0)", "SA(5.0)"]
aggs = ["mean", "0.005", "0.01", "0.025", "0.05", "0.1", "0.2", "0.5", "0.8", "0.9", "0.95", "0.975", "0.99", "0.995"]
locations = "NZ_0_2_NB_1_1"
logic_tree_file = "SLT_TAG_FINAL.json"

[debug]
location_limit = 30
