name: Dev workflow

on:
  schedule:
    - cron:  '15 2 * * 0' # At 02:15 on Sunday
  pull_request:
    branches: [main, deploy-test]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-test-workflow:
      uses: GNS-Science/nshm-github-actions/.github/workflows/python-run-tests.yml@main
      with:
        operating-systems: "['ubuntu-latest', 'macos-latest', 'windows-latest']"
        python-versions: "['3.9', '3.10']"
        delete-poetry-lock: ${{ github.event_name == 'schedule' }} # the scheduled build tests against newer dependencies
      secrets: inherit
