name: Dev workflow

on:
  pull_request:
    branches: [main, deploy-test]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-test-workflow:
      uses: GNS-Science/nshm-github-actions/.github/workflows/python-run-tests.yml@feature/create-test-workflow
      with:
        # re-enable ubuntu after https://github.com/GNS-Science/toshi-hazard-post/issues/62
        # re-enable windows after https://github.com/GNS-Science/toshi-hazard-post/issues/63
        operating-systems: "['ubuntu-latest', 'macos-latest', 'windows-latest']"
        python-versions: "['3.9']" #"['3.9', '3.10']"
      secrets: inherit
